name: Build and Deploy Marp Talks to GitHub Pages

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Marp CLI
        run: npm install -g @marp-team/marp-cli

      - name: Prepare output directory
        run: mkdir -p public

      - name: Build Marp talks to HTML
        run: |
          while IFS= read -r file; do
            [ -z "$file" ] && continue
            case "$file" in \#*) continue ;; esac
            out="public/$(basename "$file" .md).html"
            if ! marp "$file" --html --allow-local-files --output "$out"; then
              echo "Error while converting $file"
            fi
          done < .marp-talks

      - name: Add index.html listing all talks
        run: |
          echo '<!DOCTYPE html><html><head><meta charset="utf-8"><title>Daniel Lemire Talks</title><link rel="stylesheet" href="styles.css"></head><body><h1>Talks</h1><ul>' > public/index.html
          while IFS= read -r file; do
            [ -z "$file" ] && continue
            case "$file" in \#*) continue ;; esac
            talkname=$(basename "$file" .md)
            echo "<li><a href='$talkname.html'>$talkname</a></li>" >> public/index.html
          done < .marp-talks
          echo '</ul></body></html>' >> public/index.html
          cp css/styles.css public/ || true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
